// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJSsoxlvA5GYYipDLv2qIfTwZcxVDni2A',
    appId: '1:794575466397:web:0f10cdcad3ded3e85b8974',
    messagingSenderId: '794575466397',
    projectId: 'doctorclone-7e8ca',
    authDomain: 'doctorclone-7e8ca.firebaseapp.com',
    storageBucket: 'doctorclone-7e8ca.appspot.com',
    measurementId: 'G-F8W019YQYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByzhUUwRX6j3o3meR2rT3LTZcrtEky2Tk',
    appId: '1:794575466397:android:fc7d60f017d67f265b8974',
    messagingSenderId: '794575466397',
    projectId: 'doctorclone-7e8ca',
    storageBucket: 'doctorclone-7e8ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf3cg4BspWPTlbfYeVEze-Mtwz8IKEfrU',
    appId: '1:794575466397:ios:ae807c25b9891df85b8974',
    messagingSenderId: '794575466397',
    projectId: 'doctorclone-7e8ca',
    storageBucket: 'doctorclone-7e8ca.appspot.com',
    androidClientId: '794575466397-9j8ehl1or8pl9hapm2patpblvei2c926.apps.googleusercontent.com',
    iosClientId: '794575466397-sf0vho6ubk2a707kl9a26i5cvhf744b8.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorClone',
  );

}